# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf01a0a29d79b762b597aabf8eb0d1b0"
name = "d-ntwrk-axs"
handle = "d-ntwrk-axs"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "mm-d-ntwrk-axs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_checkouts,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
