api_version = "unstable"

[[extensions]]
handle = "validation-using-network-axs"
name = "t:name"
description = "t:description"
type = "function"

[[extensions.targeting]]
target = "purchase.validation.fetch"
input_query = "src/fetch.graphql"
export = "fetch"


[[extensions.targeting]]
target = "purchase.validation.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/"
details = "/"
